Geocoding Vocabulary
opengeospatial/ogc-geosparql pull request #537
Opened 2024-07-16 15:18 UTC by situx

This pull request collects URIs and classes for Geocoding Systems which should be registered at the OGC Naming Authority.

The URIs defined in this vocabulary should eventually after review by OGC be used in GeoCode Literals.

2024-08-04 23:26 UTC, nicholascar commented
Can this vocabulary be:

- [ ] proposed not as a class hierarchy but a SKOS ConceptScheme 
    - [ ] like other GeoSPARQL support vocabs with appropriate metadata
    - [ ] with Concepts dual classed as `rdfs:Datatype` objects also
    - [ ] using GeoCode as the parent with others all `skos:narrower`
- [ ] in longturtle RDF format
    * for better Git tracking
    * to remove Protege cruft
    * use https://tools.dev.kurrawong.ai/convert
- [ ] use `schema:citation` instead of `rdfs:isDefinedBy` as the targets are non-RDF nodes
- [ ] provide at least a single-line description for each one
- [ ] using Register Ontology Status Codes for the ConceptScheme and each Concept
    - so they are ready for management of additions, deprecations etc.

I'm listing all these points to see if you all agree to them but I'm not suggesting you (@situx) have to do them all yourself! You've already done the main work here, so I'm happy to do many of these, if you agree to them

2024-08-05 20:08 UTC, situx commented
Hi Nick,

I agree with all of your points. I only have a question concerning the SKOS decision:
- What would be the benefit in defining it as as SKOS concept hierarchy? The ability to define it also as rdf:Datatype? Or does it integrate better with OGC Rainbow? I am asking since we also did not define the Simple Features vocab as SKOS and we would also not define the CRS ontology as such.

2024-10-03 11:57 UTC, VladimirAlexiev requested changes

2024-10-03 11:57 UTC, VladimirAlexiev commented on vocabularies/geocoding.ttl
> +    a owl:Ontology, skos:ConceptScheme ;
if it has no members that are skos:Concept and point to it using skos:inScheme, 
then it's not a ConceptScheme

2024-11-01 15:50 UTC, VladimirAlexiev requested changes

2024-11-01 15:50 UTC, VladimirAlexiev commented on vocabularies/geocoding.ttl
> +        skos:inScheme <http://opengis.net/ont/geocode/GeoCodes> ;
@situx you inserted "inScheme" between the two RDF types, so now the syntax is invalid.

2025-01-26 00:06 UTC, situx commented
@nicholascar I think I have done most of the changes you requested here.
Could you check and correct what you think is missing?
Then we could get this pull request merged next time.

2025-03-19 19:42 UTC, mperry455 approved these changes
Looks good. Just marked a couple of typos.

2025-03-19 19:42 UTC, mperry455 commented on vocabularies/geocoding.ttl
> +    skos:definition "A location identifier code used within the North Amerian telecommunications industry to specify the location and function to telecommunications equipment" ;
Type "Amerian" -> "American"

2025-03-19 19:42 UTC, mperry455 commented on vocabularies/geocoding.ttl
> +    schema1:citation "https://web.archive.org/web/20121227195936/http://www.openpostcode.org/other-codes/geohash-36"^^xsd:anyURI ;
Strange looking URI here. Is this correct?

2025-03-19 20:46 UTC, jabhay commented
@VladimirAlexiev , could you pls take a look at the final product and approve or comment.

2025-03-19 20:49 UTC, nicholascar approved these changes

2025-04-02 20:40 UTC, merged